### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by lazarinos** [forest0xia/dota2bot-OpenHyperAI#2]
Dynamic item swapping. Perhaps you could add a way for bots to switch their items during cooldown, like the magic sticks, swapping for another item. This could also work with the refresher, etc.

**Comment by forest0xia** [comment]
Thanks lazarinos. Bots do swap some items. but yea a better swapping strategy would be good. Tho i don't think switch item during cooldown is a directly good strategy because items like refresher we almost always dont want to swap just because its in cd. this is because if you swap, the cd time gets doubled, and you dont get the regens the refresher provides. There are good aspect about swap for sure, if you can provide more specific suggestion I would be more appreciated.
