### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lazarinos** [forest0xia/dota2bot-OpenHyperAI#20]
Do you know if it could be integrated in some way with Dota Buff, to make item purchasing more dynamic and less repetitive, based on the heroes you're facing?

**Comment by forest0xia** [comment]
You will probably find someone else to work with that also interested on this topic. 😄

**Comment by forest0xia** [comment]
You can reopen this later if you have more specific suggestion like how exactly we should do it. As of now I don't feel necessary and it may only make bots weaker - what works for human are not necessarily the best for bots. Keep in mind bots can't utilize items as good as human because they don't do item combos well. I look for your specific suggestion on the exact improvements or your PR. Thanks
