### ISSUE TITLE
feedback-2024-9-10

### ISSUE THREAD

**Issue by AlexLWT** [forest0xia/dota2bot-OpenHyperAI#24]
您好, 您的机器人脚本现在没有效果, 进入游戏并选择"本地主机"后会等待很久, 最终变成原始(默认)机器人脚本
这是最近更新出现的问题, 我已经尝试重新订阅, 但仍然没有效果
同时, 我希望在修复此问题后可以修复多个人在不同阵营的对局时出现的机器人无法购买物品的bug
最后还要反馈几个问题:
1. 机器人不会使用中立物品
2. 机器人经常经济很低
3. 机器人对线不够聪明, 很容易就被滚雪球了
4. 关于人类玩家推塔, 希望机器人能更聪明判断是否需要回去支援

--------------------

Hello, your bot script is currently not working, entering the game and selecting "Local Host" will wait a long time and eventually become the original (default) bot script
This is a problem with a recent update, I have tried to re-subscribe, but it still doesn't work
At the same time, I hope that after fixing this issue, I can fix the bug that the robot can not buy items when multiple people are in different sides of the game
Finally, there are a few feedback questions:
1. The robot will not use neutral items
2. Robots often have a low economy
3. The robot is not smart enough for the line and can easily be snowballed
4. As for human players pushing towers, I hope robots will be more intelligent in judging whether they need to go back for support

**Comment by forest0xia** [comment]
In general, a lot of bot issues is a Valve problem not due to any other community developer. There are issues all non-Valve developers cannot resolve. See this post: https://www.reddit.com/r/DotA2/comments/1ezxpav/a_note_to_valve_official_regarding_bot_scripts/

1. Not possible. Unless you enable the advanced mode. Follow this: https://steamcommunity.com/workshop/filedetails/discussion/3246316298/4764334012741504141/
2. Same as above
3. Can you help contributing to improve the code & logic so the bots are better later?
4. This should have been improved a lot. But in general, same response as above

**Comment by forest0xia** [comment]
It seems there were quite some people experienced issues with the script not working properly in the past couple of days. But the issue had been fixed a couple days back already. It should be a caching issue on Valve side that players cannot effectively update the scripts files by re-subscribing. Anyway, it seems most players are able to use the script now. 

Try again. And I suggest to enable the advanced mode. Follow this: https://steamcommunity.com/workshop/filedetails/discussion/3246316298/4764334012741504141/

**Comment by forest0xia** [comment]
I'm closing this since there is nothing to follow up on that I can help anytime soon. The mentioned issues are on todo list already and there is no quick plan to address those soon - it's not an easy problem.
