### ISSUE TITLE
Strange experience

### ISSUE THREAD

**Issue by JoKingT800** [forest0xia/dota2bot-OpenHyperAI#29]
The opposing BOTs are grouping together, and the teammate BOTs are going up like individuals to give away heads

**Comment by forest0xia** [comment]
try to ping the bots to do things you want. may not always do what you want because i do not have the time to make improvements to support the ping command for many situations. but just try it.

You are not a bot, you dont follow what bots do so bots dont seem to group up with you. That's ultimately the actual reason

**Comment by forest0xia** [comment]
I dont have a plan to add this layer of cooperation between human + bots. So for now, try you best to lead or work with your ally bots. Or help me to build this layer of support.

**Comment by JoKingT800** [comment]
OK, I understand
