### ISSUE TITLE
Got the bots working with 7.37d

### ISSUE THREAD

**Issue by mikkokeskinen** [forest0xia/dota2bot-OpenHyperAI#32]
The bots didn't work with 7.37d. Got these kind of errors in the console:

```
LoadScript: ...apps\workshop\content\570\3246316298\hero_selection.lua, scope name HeroSelectionScriptScope
[VScript] Script Runtime Error: ...eamapps\workshop\content\570\3246316298\FunLib\utils.lua:343: module 'bots.ts_libs.dota.index' not found:
    no field package.preload['bots.ts_libs.dota.index']Failed to find scripts\vscripts\bots/ts_libs/dota/index.lua
stack traceback:
    [C]: in function 'require'
    ...eamapps\workshop\content\570\3246316298\FunLib\utils.lua:343: in main chunk
    [C]: in function 'require'
    ...p\content\570\3246316298\FunLib\aba_global_overrides.lua:2: in main chunk
    [C]: in function 'require'
    ...mapps\workshop\content\570\3246316298\hero_selection.lua:1: in main chunk
Failed to run script '...apps\workshop\content\570\3246316298\hero_selection.lua'!
```

I changed these kind of lines:

`local ____dota = require("bots.ts_libs.dota.index")`

to

`local ____dota = require(GetScriptDirectory().."/ts_libs/dota/index")`

And the bots work again!

**Comment by forest0xia** [comment]
Thanks a lot for reporting this issue with the exact details needed and even with the fix you came up with. Appreciated. 

It would probably take a much longer time to realize the normal game play isnt gonna work because of this issue. This is due to the fact we tried to introduce typescript to the code base and in typescript we use `bots` as the filepath to resolve the path for ts and thus this caused issue for the generated lua files.

**Comment by forest0xia** [comment]
Addressed this in commit https://github.com/forest0xia/dota2bot-OpenHyperAI/commit/d6307a31a56b5c3717d046483b3191d486f2c3fb

**Comment by forest0xia** [comment]
@mikkokeskinen please try to use the latest version available in Workshop see if that works. maybe re-subscribe to the script. I want to make sure the version there is working for ppl besides me.
