### ISSUE TITLE
About the unsupported heroes

### ISSUE THREAD

**Issue by IMJoyJ** [forest0xia/dota2bot-OpenHyperAI#7]
(From https://steamcommunity.com/sharedfiles/filedetails/?id=3246316298)
Unsupported heroes: Dark Willow, Elder Titan, Hoodwink, io, Lone Druid, Marci, Muerta, Primal Beast

I'm curious to see what happens when AI controls these heroes.
I know there is no way to use Muerta's first skill precisely for now, for there is no API to use vector skills. The same problem happens to Marci. I have no idea about Elder Titan, IO, and Primal Beast. I believe I have seen an io AI before, am I wrong?

I wrote a script for Muerta a while back; she tends to stay away from the front line for no reason. This makes me think of when I use Phoenix and start with Sunray skill in mid: any enemy AI hero stays away from me from level 1. Maybe the damage calculation goes wrong somewhere?

BTW only hero_wisp.Lua (IO) is missing in BotLib. Is it Intentional or unintentional?

**Comment by forest0xia** [comment]
Intentional in a way that it's basically my least played/interested hero anyways and I have no idea how it should get implemented to be a good one.

Regarding - "I'm curious to see what happens when AI controls these heroes."

Those buggy heroes will not be able to do laning or any other defaults modes that we haven't overridden. That means if those bots are in any of the laning, roam, attack, etc modes, they will be doing nothing but keep going enemy base or feed into towers/heroes until their hp get so low and triggered their retreat mode to go back to their fountain but it's usually too late and they mostly just die there.

Those heroes need a more extensive takeover care which requires the devs to do much more work for them.

**Comment by forest0xia** [comment]
If you want to see how they perform in game. just type `!pick npc_dota_hero_muerta`, or `npc_dota_hero_elder_titan` for example in game hero selection phase.
They have half chance to perform like totally broken
